PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX psdo: <http://purl.obolibrary.org/obo/psdo#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT ?label ?subject ?desc
WHERE {
	?subject a owl:Class.
  ?subject rdfs:label ?label.
	?subject obo:IAO_0000115 ?desc.

	FILTER (!regex(str(?label), "^obsolete"))
}
